services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
      - MARIADB_ROOT_PASSWORD=my_password
  backend:
    container_name: laravel
    image: bitnami/laravel:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    volumes:
      - ./backend:/app
  
  frontend:
    container_name: api-consumer
    image: juanpb/acceso-datos-docker:v1.0.1
    restart: unless-stopped
    ports:
      - "80:80"